"""Response models for user-owned trading signals."""

from typing import Any, Dict, Optional

from pydantic import BaseModel


class SignalResponse(BaseModel):
    """A signal generated by the authenticated user's engine session."""

    id: int
    time: str
    symbol: str
    price: float
    rule_id: Optional[int]
    user_id: str
    indicators: Optional[Dict[str, Any]] = None
    created_at: str
